---
title: "Fiddler Crab Tasks"
author: "Desik Somasundaram"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(kableExtra)
library(ggrepel)
```

```{r include=FALSE}
fiddler_crab_sizes <- read_csv(here("data", "HTL-MAR-FiddlerCrabBodySize.csv" ))

```

```{r include=FALSE}
fiddler_crab_clean <- clean_names(fiddler_crab_sizes)

```

```{r, fig.alt= "Jitter plot of crab carapace width in millimeters at different latitudes showing that as latitude increases, carapace width tends to increase"}
crabs_plot <- ggplot(fiddler_crab_clean, aes(x = latitude, y = carapace_width)) +
  geom_jitter() + 
  labs(title = "Carapace width of crabs at different latitudes", x = "Latitude", y = "Carapace width (mm)")

crabs_plot
```

### Jitter plot of crab carapace width (mm) in salt marshes from Florida to Massachusetts based on latitude

```{r echo=FALSE}
summary_carpace <- fiddler_crab_clean %>%
  group_by(site) %>% 
  summarize(mean = round(mean(carapace_width),2), sd = round(sd(carapace_width),2), n = n())

summary_table_carp <- summary_carpace %>% 
  kable(col.names = c("Site", "Mean of Carapace Width (mm)", "Standard Deviation (mm)", "Number of Observations")) %>%
  kable_classic(full_width = FALSE)
  
  
summary_table_carp
  
```
### Table showing the mean, standard deviation and number of observations for crab carapace width by site

```{r include=FALSE}
summary_water <- fiddler_crab_clean %>% 
  group_by(site) %>% 
  summarize(mean_matw = mean(matw))

summary_updated <- summary_carpace %>% 
  left_join(summary_water)

```


```{r, echo= FALSE, fig.alt= "Scatter plot of mean carapace width by mean water temperature based on site showing carapace width decreasing with increased water temperature"}

summary_plot <- ggplot(summary_updated, aes(x = mean_matw, y = mean)) +
  geom_point() +
  labs(title = "Mean carapace width by mean water temperature based on site", x = "Mean annual water temperature (degrees celsius)", y = "Mean carapace width (mm)") +
  geom_text_repel(aes(label = site), size = 2.5) +
  theme_minimal()
  
  

summary_plot
```

### Mean carapace width by mean water temperature based on site along the U.S. east coast


